default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hogwarts_crud_development

test:
  <<: *default
  database: hogwarts_crud_test

production:
  <<: *default
  database: hogwarts_crud_production
  username: hogwarts_crud
  password: <%= ENV['HOGWARTS_CRUD_DATABASE_PASSWORD'] %>
